// Three.js is bundled in vendor/ so this works from file:// as well as a local server.
const canvas=document.querySelector('#game'),wrap=document.querySelector('#canvas-wrap'),THREE=window.THREE;
const ui={name:document.querySelector('#unit-name'),cls:document.querySelector('#unit-class'),move:document.querySelector('#unit-move'),range:document.querySelector('#unit-range'),hp:document.querySelector('#hp-value'),bar:document.querySelector('#hp-bar'),log:document.querySelector('#log'),hint:document.querySelector('#hint'),mission:document.querySelector('#mission-label'),objective:document.querySelector('#objective'),modal:document.querySelector('#modal'),kicker:document.querySelector('#modal-kicker'),title:document.querySelector('#modal-title'),copy:document.querySelector('#modal-copy'),modalButton:document.querySelector('#modal-button'),battle:document.querySelector('#battle-scene'),attacker:document.querySelector('#battle-attacker'),defender:document.querySelector('#battle-defender'),result:document.querySelector('#battle-result'),battleButton:document.querySelector('#battle-continue')};
const renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x252b25);scene.fog=new THREE.Fog(0x252b25,12,27);const camera=new THREE.OrthographicCamera(-6,6,6,-6,.1,100);camera.position.set(8,10,10);camera.lookAt(0,0,0);scene.add(new THREE.HemisphereLight(0xe9e0bc,0x29332a,2.4));const light=new THREE.DirectionalLight(0xffe0a0,2.6);light.position.set(-5,9,4);light.castShadow=true;scene.add(light);const board=new THREE.Group();scene.add(board);const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();
const classes={sword:{icon:'✦',color:0xd6d8d1,move:3,range:1},spear:{icon:'↟',color:0x69a9b6,move:3,range:1},axe:{icon:'✚',color:0xd6924c,move:2,range:1},bow:{icon:'⌁',color:0x8bb866,move:3,range:2}};
const missions=[{objective:'Secure the old bridge.',players:[['Ari','sword',0,4],['Moss','spear',1,3]],enemies:[['Raider','axe',5,1],['Raider','axe',5,3],['Lookout','bow',4,4]]},{objective:'Clear the forest pass.',players:[['Ari','sword',0,3],['Moss','spear',1,4],['Nia','bow',0,5]],enemies:[['Brigand','axe',4,1],['Pikeman','spear',5,3],['Brigand','axe',4,5]]},{objective:'Break the hill blockade.',players:[['Ari','sword',0,2],['Moss','spear',0,4],['Nia','bow',1,3]],enemies:[['Guard','sword',4,1],['Guard','axe',5,2],['Pikeman','spear',4,4],['Guard','sword',5,5]]},{objective:'Defeat the Iron Captain.',players:[['Ari','sword',0,3],['Moss','spear',1,2],['Nia','bow',1,4]],enemies:[['Guard','axe',4,1],['Guard','spear',4,5],['IRON CAPTAIN','axe',5,3,14]]}];
let units=[],selected=null,phase='player',missionIndex=0,sound=true,battleBusy=false,closeBattle=null,audio=null,musicTimer=null,musicStep=0;
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));const alive=unit=>units.includes(unit);const dist=(a,b)=>Math.abs(a.x-b.x)+Math.abs(a.y-b.y);const occupied=(x,y)=>units.find(u=>u.x===x&&u.y===y);const advantage=(a,b)=>(a==='axe'&&b==='sword')||(a==='sword'&&b==='spear')||(a==='spear'&&b==='axe');
function chip(freq,length=.1,type='square',volume=.035,delay=0){if(!audio||!sound||!freq)return;const t=audio.currentTime+delay,o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(volume,t+.008);g.gain.exponentialRampToValueAtTime(.0001,t+length);o.connect(g).connect(audio.destination);o.start(t);o.stop(t+length+.02)}
function stopMusic(){if(musicTimer){clearTimeout(musicTimer);musicTimer=null}}
function musicLoop(){if(!sound||!audio){musicTimer=null;return}const melody=[659,784,880,784,659,587,523,587,659,784,988,784,659,587,523,0],bass=[131,147,165,147];const step=musicStep++%melody.length;chip(melody[step],.12,'square',.018);if(step%4===0)chip(bass[(step/4)%bass.length],.24,'triangle',.026);musicTimer=setTimeout(musicLoop,145)}
function startMusic(){if(sound&&audio&&!musicTimer)musicLoop()}
function unlockAudio(){if(!sound)return;try{if(!audio)audio=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume().then(startMusic);else startMusic()}catch{}}
function sfx(kind){unlockAudio();if(!audio||!sound)return;const n=audio.currentTime;if(kind==='click')chip(880,.045,'square',.03);if(kind==='select'){chip(523,.05,'square',.028);chip(784,.07,'square',.024,.045)}if(kind==='move'){chip(440,.05,'square',.025);chip(587,.07,'square',.023,.055)}if(kind==='attack'){chip(150,.07,'sawtooth',.045);chip(95,.12,'square',.04,.035)}if(kind==='counter'){chip(196,.06,'square',.035);chip(131,.12,'sawtooth',.035,.04)}if(kind==='death'){chip(330,.07,'square',.035);chip(247,.07,'square',.03,.07);chip(165,.16,'triangle',.04,.14)}if(kind==='victory'){chip(523,.09,'square',.032);chip(659,.09,'square',.03,.09);chip(784,.18,'square',.03,.18)}if(kind==='gameover'){chip(330,.12,'square',.04);chip(247,.12,'square',.04,.13);chip(165,.35,'triangle',.05,.26)}}
function log(text){ui.log.insertAdjacentHTML('afterbegin',`<div class="log-entry">${text}</div>`)}function hint(text){ui.hint.textContent=text}
function makeUnit(name,type,x,y,team,hp=10){const info=classes[type],g=new THREE.Group(),metal=new THREE.MeshStandardMaterial({color:info.color,metalness:.7,roughness:.25}),wood=new THREE.MeshStandardMaterial({color:0x5b3824,roughness:.8}),body=new THREE.Mesh(new THREE.CylinderGeometry(.29,.36,.65,6),new THREE.MeshStandardMaterial({color:team==='player'?0x2d6572:0x873c36,roughness:.75}));body.position.y=.38;body.castShadow=true;g.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.19,12,8),new THREE.MeshStandardMaterial({color:0xf0c58d}));head.position.y=.82;g.add(head);const weapon=new THREE.Group();weapon.position.set(.28,.62,0);weapon.rotation.z=-.35;if(type==='sword'){const blade=new THREE.Mesh(new THREE.BoxGeometry(.09,.62,.1),metal);blade.position.y=.22;weapon.add(blade);const guard=new THREE.Mesh(new THREE.BoxGeometry(.38,.06,.1),metal);guard.position.y=-.08;weapon.add(guard)}if(type==='spear'){const shaft=new THREE.Mesh(new THREE.CylinderGeometry(.027,.027,1.05,6),wood);shaft.position.y=.18;weapon.add(shaft);const tip=new THREE.Mesh(new THREE.ConeGeometry(.1,.28,4),metal);tip.position.y=.83;weapon.add(tip)}if(type==='axe'){const handle=new THREE.Mesh(new THREE.CylinderGeometry(.035,.035,.68,6),wood);handle.position.y=.15;weapon.add(handle);const axehead=new THREE.Mesh(new THREE.BoxGeometry(.32,.23,.11),metal);axehead.position.set(.1,.4,0);weapon.add(axehead)}if(type==='bow'){const bow=new THREE.Mesh(new THREE.TorusGeometry(.25,.025,6,16,Math.PI),metal);bow.rotation.z=Math.PI/2;weapon.add(bow);const string=new THREE.Mesh(new THREE.CylinderGeometry(.009,.009,.5,4),new THREE.MeshBasicMaterial({color:0xe8dfc7}));string.rotation.z=Math.PI/2;weapon.add(string)}weapon.traverse(o=>o.castShadow=true);g.add(weapon);g.position.set(x-2.5,0,y-2.5);board.add(g);return {name,type,x,y,team,hp,maxHp:hp,moved:false,acted:false,mesh:g}}
function setup(){board.clear();units=[];selected=null;phase='player';battleBusy=false;ui.log.innerHTML='';ui.modal.classList.add('hidden');ui.battle.classList.add('hidden');const m=missions[missionIndex];ui.mission.textContent=`MISSION 0${missionIndex+1}`;ui.objective.textContent=m.objective;for(let x=0;x<6;x++)for(let y=0;y<6;y++){const t=new THREE.Mesh(new THREE.BoxGeometry(.94,.12,.94),new THREE.MeshStandardMaterial({color:(x+y)%2?0x66735a:0x798166,roughness:1}));t.position.set(x-2.5,-.08,y-2.5);t.receiveShadow=true;t.userData={tile:true,x,y};board.add(t)}m.players.forEach(([n,t,x,y])=>units.push(makeUnit(n,t,x,y,'player')));m.enemies.forEach(([n,t,x,y,h])=>units.push(makeUnit(n,t,x,y,'enemy',h||10)));log('Your force reaches the field.');updateUI();hint('Select a blue unit.')}
function updateUI(){if(!selected||!alive(selected)){ui.name.textContent='—';ui.cls.textContent=ui.move.textContent=ui.range.textContent=ui.hp.textContent='—';ui.bar.style.width='0';return}const c=classes[selected.type];ui.name.textContent=selected.name;ui.cls.textContent=selected.type.toUpperCase();ui.move.textContent=c.move;ui.range.textContent=c.range;ui.hp.textContent=`${Math.max(0,selected.hp)}/${selected.maxHp}`;ui.bar.style.width=`${Math.max(0,selected.hp)/selected.maxHp*100}%`}
function clearTiles(){board.children.filter(o=>o.userData.tile).forEach(t=>t.material.color.setHex((t.userData.x+t.userData.y)%2?0x66735a:0x798166))}function resetEmissive(){units.forEach(u=>u.mesh.children[0].material.emissive.setHex(0))}
function select(unit){selected=unit;clearTiles();resetEmissive();if(unit.team==='enemy'){hint(`${unit.name} is an enemy. Its class and HP are shown in the panel.`);sfx('select')}else{const move=classes[unit.type].move;board.children.filter(o=>o.userData.tile).forEach(t=>{const d=Math.abs(t.userData.x-unit.x)+Math.abs(t.userData.y-unit.y);if(d>0&&d<=move&&!occupied(t.userData.x,t.userData.y)&&!unit.moved&&!unit.acted)t.material.color.setHex(0x3e7d91)});units.filter(e=>e.team==='enemy'&&dist(unit,e)===classes[unit.type].range&&!unit.acted).forEach(e=>e.mesh.children[0].material.emissive.setHex(0x882222));hint(unit.acted?'This unit has acted. Choose another unit.':unit.moved?'Choose an enemy in range.':'Choose a blue tile to move, or a red enemy to attack.');sfx('select')}updateUI()}
function fighter(unit,role){const c=classes[unit.type];return `<span class="fighter-label">${role}</span><span class="fighter-icon" style="color:#${c.color.toString(16).padStart(6,'0')}">${c.icon}</span><strong>${unit.name}</strong><small>${unit.type.toUpperCase()} · ${Math.max(0,unit.hp)}/${unit.maxHp} HP</small>`}
function dismissBattle(){if(!closeBattle)return;sfx('click');ui.battle.classList.add('hidden');battleBusy=false;const resolve=closeBattle;closeBattle=null;resolve()}
function battleScene(a,b,dealt,counter){battleBusy=true;ui.attacker.innerHTML=fighter(a,'ATTACKER');ui.defender.innerHTML=fighter(b,'DEFENDER');ui.result.innerHTML=`<span>${a.name} deals <b>${dealt}</b> damage</span><span>${counter?`${b.name} counters for <b>${counter}</b>`:`${b.name} cannot counter`}</span>`;ui.battle.classList.remove('hidden');return new Promise(resolve=>{closeBattle=resolve})}
async function attack(a,b){if(!alive(a)||!alive(b))return false;const dealt=advantage(a.type,b.type)?5:advantage(b.type,a.type)?2:3,counter=classes[b.type].range===dist(a,b)?(advantage(b.type,a.type)?4:2):0;await battleScene(a,b,dealt,counter);b.hp-=dealt;sfx('attack');log(`${a.name} strikes ${b.name} for ${dealt}.`);b.mesh.position.y=.18;setTimeout(()=>{if(alive(b))b.mesh.position.y=0},130);if(b.hp<=0){sfx('death');log(`${b.name} falls.`);board.remove(b.mesh);units=units.filter(u=>u!==b);if(selected===b)selected=null}else if(counter&&alive(a)){a.hp-=counter;sfx('counter');log(`${b.name} counters for ${counter}.`);if(a.hp<=0){sfx('death');log(`${a.name} falls.`);board.remove(a.mesh);units=units.filter(u=>u!==a);if(selected===a)selected=null}}resetEmissive();updateUI();return checkEnd()}
function checkEnd(){if(!units.some(u=>u.team==='enemy')){phase='done';sfx('victory');setTimeout(()=>showModal('MISSION COMPLETE',missionIndex===3?'THE PATH IS YOURS':'The road opens ahead.',missionIndex===3?'You broke the captain’s line. The valley is safe.':'No speeches. The company marches on.',missionIndex===3?'PLAY AGAIN':'NEXT MISSION'),200);return true}if(!units.some(u=>u.team==='player')){phase='done';sfx('gameover');setTimeout(()=>showModal('GAME OVER','THE COMPANY HAS FALLEN','All of your troops were defeated. Return to the start of this battle.','RETRY MISSION'),200);return true}return false}function showModal(k,t,c,b){ui.kicker.textContent=k;ui.title.textContent=t;ui.copy.textContent=c;ui.modal.classList.remove('hidden')}
async function endTurn(){if(phase!=='player'||battleBusy)return;sfx('click');selected=null;clearTiles();resetEmissive();updateUI();phase='enemy';hint('Enemy turn…');log('— ENEMY TURN —');await wait(400);for(const e of [...units.filter(u=>u.team==='enemy')]){if(!alive(e)||phase==='done')break;const targets=units.filter(u=>u.team==='player');if(!targets.length)break;const target=[...targets].sort((a,b)=>dist(a,e)-dist(b,e))[0],range=classes[e.type].range;if(dist(e,target)>range){const options=[[-1,0],[1,0],[0,-1],[0,1]].map(([x,y])=>({x:e.x+x,y:e.y+y})).filter(p=>p.x>=0&&p.x<6&&p.y>=0&&p.y<6&&!occupied(p.x,p.y)).sort((a,b)=>Math.abs(a.x-target.x)+Math.abs(a.y-target.y)-Math.abs(b.x-target.x)-Math.abs(b.y-target.y));if(options[0]){e.x=options[0].x;e.y=options[0].y;e.mesh.position.set(e.x-2.5,0,e.y-2.5);sfx('move');await wait(160)}}if(alive(e)&&alive(target)&&dist(e,target)===range){await attack(e,target);if(phase==='done')return}}if(checkEnd())return;phase='player';units.filter(u=>u.team==='player').forEach(u=>{u.moved=false;u.acted=false});hint('Your turn. Select a unit.');log('— YOUR TURN —')}
canvas.addEventListener('pointerdown',async ev=>{unlockAudio();if(phase!=='player'||battleBusy)return;const r=canvas.getBoundingClientRect();pointer.set((ev.clientX-r.left)/r.width*2-1,-(ev.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hits=ray.intersectObjects(board.children,true);if(!hits.length)return;let o=hits[0].object;while(o.parent&&o.parent!==board)o=o.parent;const unit=units.find(x=>x.mesh===o);if(unit){if(unit.team==='player'&&!unit.acted)select(unit);else if(unit.team==='enemy'&&selected&&selected.team==='player'&&!selected.acted&&dist(selected,unit)===classes[selected.type].range){const actor=selected;await attack(actor,unit);if(alive(actor)){actor.acted=true;actor.moved=true}updateUI()}else if(unit.team==='enemy')select(unit);return}const tile=hits.map(h=>h.object).find(x=>x.userData.tile);if(tile&&selected&&selected.team==='player'&&!selected.moved&&!selected.acted){const d=Math.abs(tile.userData.x-selected.x)+Math.abs(tile.userData.y-selected.y);if(d>0&&d<=classes[selected.type].move&&!occupied(tile.userData.x,tile.userData.y)){selected.x=tile.userData.x;selected.y=tile.userData.y;selected.mesh.position.set(selected.x-2.5,0,selected.y-2.5);selected.moved=true;sfx('move');select(selected)}}});
document.querySelector('#end-turn').onclick=endTurn;document.querySelector('#sound-button').onclick=e=>{sound=!sound;if(sound){unlockAudio();sfx('click')}else stopMusic();e.target.textContent=`SOUND: ${sound?'ON':'OFF'}`};ui.battleButton.onclick=dismissBattle;document.addEventListener('keydown',e=>{if(e.key==='Escape')dismissBattle();if(e.code==='Space'){e.preventDefault();endTurn()}if(e.key.toLowerCase()==='r'){sfx('click');setup()}});ui.modalButton.onclick=()=>{sfx('click');ui.modal.classList.add('hidden');if(!units.some(u=>u.team==='player')||missionIndex===3)missionIndex=missionIndex===3?0:missionIndex;else missionIndex++;setup()};
function resize(){const w=wrap.clientWidth,h=wrap.clientHeight;renderer.setSize(w,h,false);const a=w/h;camera.left=-6*a;camera.right=6*a;camera.top=6;camera.bottom=-6;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();setup();renderer.setAnimationLoop(()=>renderer.render(scene,camera));
